InventoryManagement/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('orderInventory/', include('orderInventory.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orderInventory/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = "inventory"
urlpatterns = [
    path('', views.index,name="home"),
    path('Category/', views.categoryHome, name="category"),
    path('CategoryNew/', views.newCategory, name="new_category"),
    path('CategoryUpdate/', views.updateCategory, name="update_category"),
    path('CategoryDelete/', views.deleteCategory, name="delete_category"),

    path('Ingredient/', views.ingredientHome ,name="ingredient"),
    path('IngredientNew/', views.newIngredient ,name="new_ingredient"),
    path('IngredientUpdate/', views.updateIngredient,name="update_ingredient"),
    path('IngredientDelete/', views.deleteIngredient,name="delete_ingredient"),

    path('Items/', views.itemsHome, name="items"),
    path('ItemNew/', views.newItems, name="new_items"),
    path('ItemEdit/<int:id>', views.editItems, name="edit_items_template"),
    path('ItemLock/<int:id>', views.lockItem, name="lock_item"),
    path('ItemsDelete/', views.deleteItems, name="delete_items"),

    path('ConfirmOrderList/', views.orderHome, name="orderList"),
    path('OrderDetail/<int:OrderID>/', views.orderDetail, name="orderDetail"),
    path('Order/', views.orderNewCreate, name="orderNewCreate"),
    path('OrderAddItems/', views.orderAddItems, name="orderAddItems"),

    path('OrderEdit/<int:id>', views.orderEditTemplate, name="orderEdit"),
    path('OrderDelete/', views.deleteOrder, name="delete_order"),
    path('OrderLock/<int:OrderId>', views.lockOrder, name="lock_order"),


    path('OrderPrintOptions/<int:orderId>', views.orderPrint, name="orderPrint"),
    path('OrderPrintData/<int:orderId>/<str:dataType>', views.orderPrintData, name="orderPrintData"),
    path('detail/', views.getDetail, name="getInfo"),

    path('OrderList/', views.clientTalks, name="clientTalksList"),

    path('test1/', views.test1, name="test"),
    path('test2/<int:OrderId>', views.test2, name="test2"),
    path('pdf1/', views.pdfGenration1, name="pdfView"),
    path('pdfHtmlView1/', views.pdfHtmlView, name="htmlView"),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# Demostrate Urls
#     - test1
#     - itemDetail/<int:id>
#     - test2/<int:orderId> //Check Detail about Items
#

orderInventory/models.py
from django.db import models
from datetime import datetime
from django.core.exceptions import ValidationError
# Create your models here.


def checkMobileNumber(value):
    if len(value) != 10:
        raise ValidationError(f'{value}s must be of 10 digits')
    value = str(value)
    if not value.isnumeric():
        raise ValidationError(f'{value} must be digits')


class Type(models.Model):
    type = models.CharField(max_length=32, unique=True)

    def __str__(self):
        return f"{self.id} : {self.type}"


class ItemIndividual(models.Model):
    name = models.CharField(max_length=64)
    type = models.ForeignKey(
        Type,
        related_name="Item_Type",
        on_delete=models.SET(None),
        null=True,
        blank=True
    )
    confirmItem = models.BooleanField(default=False)
    createdAt = models.DateTimeField(default=datetime.now)
    modifyAt = models.DateTimeField(blank=True, null=True)

    def isLock(self):
        if self.confirmItem:
            return "Item Locked"

        return ""

    def __str__(self):
        return f"{self.id} : {self.name} : {self.type} : {self.isLock()}"


class Category(models.Model):
    name = models.CharField(max_length=64)

    def __str__(self):
        return f"{self.id} : {self.name}"


class IngredientIndividual(models.Model):
    name = models.CharField(max_length=64)
    category = models.ForeignKey(
        Category,
        on_delete=models.SET_NULL,
        related_name="category",
        null=True,
    )

    def __str__(self):
        return f"{self.id} : {self.name}"

    def json(self):
        return {
            "name": self.name,
            "orderAt": self.category,
        }


class Items(models.Model):
    itemId = models.ForeignKey(
        ItemIndividual,
        on_delete=models.CASCADE,
        related_name="itemName",
    )
    ingredientId = models.ForeignKey(
        IngredientIndividual,
        on_delete=models.CASCADE,
        related_name="ingredientName",
    )
    createdAt = models.DateTimeField(default=datetime.now)
    modifyAt = models.DateTimeField(default=None, blank=True, null=True)
    deletedAt = models.DateTimeField(default=None, blank=True, null=True)

    def __str__(self):
        return f"{self.id} : {self.itemId.name} : {self.ingredientId.name} "

    # def json(self):
    #     return {
    #
    #     }

class OrderIndividual(models.Model):
    name = models.CharField(max_length=64,
                            null=True, blank=True,
                            verbose_name="Name of Function For Which this order is Placed")
    mobileNumber = models.CharField(max_length=15,validators=[checkMobileNumber])
    address = models.CharField(max_length=256,blank=True,null=True)
    numberOfPerson = models.IntegerField(blank=True,null=True)
    email = models.EmailField(blank=True,null=True)
    deliveryDate = models.DateTimeField(blank=True, null=True)
    confirmOrder = models.BooleanField(default=False)
    createdAt = models.DateTimeField(default=datetime.now)
    modifyAt = models.DateTimeField(default=None, blank=True, null=True)
    deletedAt = models.DateTimeField(default=None, blank=True, null=True)

    def __str__(self):
        return f"{self.id} : {self.name}"


class Order(models.Model):
    orderId = models.ForeignKey(
        OrderIndividual,
        related_name="orderName",
        on_delete=models.CASCADE,
        verbose_name="To track Order",
    )
    orderItem = models.ForeignKey(
        ItemIndividual,
        related_name="ItemName",
        on_delete=models.CASCADE,
        verbose_name="Items With Ingredient Which need to Order",
        null=True
    )
    createdAt = models.DateTimeField(default=datetime.now)
    modifyAt = models.DateTimeField(default=None, blank=True, null=True)
    deletedAt = models.DateTimeField(default=None, blank=True, null=True)

    def __str__(self):
        deleteStr = ""
        if self.deletedAt != None:
            deleteStr = "Deleted"

        return f"{self.id} : {self.orderId} : {self.orderItem.name} : {deleteStr}"

orderInventory/views.py
from django.core import serializers

from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from django.views.decorators.cache import cache_control
from django.views.decorators.csrf import csrf_exempt

from django.utils import timezone
from weasyprint import HTML, CSS

from django.template.loader import get_template, render_to_string
from django.conf import settings
import tempfile

from django_weasyprint import WeasyTemplateResponse

import encodings
from . import models
from datetime import datetime
import json
import io


####################################################
# Try WeasyPrint Library For Generating PDF
####################################################

# Create your views here.


# Main Functions that render template

@cache_control(max_age=3600)
def index(request):
    """
        Display Recent Orders list
    """
    order = models.OrderIndividual.objects.filter(deliveryDate__gte=datetime.now(),deletedAt=None,confirmOrder=True).order_by("deliveryDate")
    return render(request, 'index.html', {
        "toolbar": True,
        "putPlus": True,
        "active": "home",
        "data": order,
        "heading": "Recent Files",
    })


#####################################################
################# Category Functions  #################
#####################################################

@cache_control(max_age=3600)
def categoryHome(request):
    """
        Display List of Category
    """
    category = models.Category.objects.all()
    return render(request, 'category.html', {
        "toolbar": True,
        "putPlus": True,
        "active": "category_tab",
        "data": category,
        "queryItem": "category_one",
        "heading": "Category",
    })


def newCategory(request):
    """
        Add new Category DAta to Database
        input :- Accept all Necessary data from User through Form
        output : Redirect to list of Category
    """
    if request.method == "POST":
        new_category = models.Category()
        new_category.name = request.POST.get("name")
        new_category.save()

    return redirect('inventory:category')


def updateCategory(request):
    """
        Update Category Data to Database
        input :  Accept Name and  Id
        output : Redirect to list of Category
    """
    if request.method == "POST":
        update_category = models.Category.objects.get(id=request.POST.get("updateElementID"))
        # retrieve Category updated data from user
        update_category.name = request.POST.get("name")

        # print("After Category :- ", update_category)
        update_category.save()

    return redirect('inventory:category')


# not Access using UI We have to give give direct URL
def deleteCategory(request):
    """
        Delete Category Data to Database
        input :- Accept only Category Id
        output : Redirect to list of Category
    """
    msg = "Invalid Category ID"
    if request.method == "GET":
        print("Delete Category Method")
        deleteCategory = models.Category.objects.get(id=request.GET.get("deleteElementId"))

        print("Delete Element :- ", deleteCategory)
        deleteCategory.delete()
        msg = f"Category {deleteCategory.name} with Id {deleteCategory.id} is Deleted Successfully"

    return JsonResponse({
        "Status": 200,
        "Message": msg,
    })


#####################################################
############ Ingredient Functions  #################
#####################################################

@cache_control(max_age=3600)
def ingredientHome(request):
    """
        Display list of Ingredient
    """
    ingredients = models.IngredientIndividual.objects.all()
    category = models.Category.objects.all()
    return render(request, 'ingredient.html', {
        "toolbar": True,
        "putPlus": True,
        "active": "ingredient",
        "data": ingredients,
        "Category": category,
        "queryItem": "ingredient_one",
        "heading": "Ingredients",
    })


@csrf_exempt
def newIngredient(request):
    """
        Add new IIngredient Data to Database
        input :- Accept all Necessary data for new Ingredient from User through Form
        output : Redirect to list of Ingredient
    """
    if request.method == "POST":
        ingre = models.IngredientIndividual(name=request.POST.get("name"), category_id=request.POST.get("categoryId"))
        ingre.save()
        if request.POST.get("json") == "1":
            return JsonResponse({
                "status": 200,
                "newIngredientId": ingre.id
            })
    return redirect('inventory:ingredient')


def updateIngredient(request):
    """
        Update IIngredient Data to Database
        input :- Accept all Necessary data from User through Form along with Ingredient ID
        output : Redirect to list of Ingredient
    """
    if request.method == "POST":
        ingre = models.IngredientIndividual.objects.get(id=request.POST.get("updateElementID"))
        ingre.name = request.POST.get("name")
        ingre.category_id = request.POST.get("categoryId")
        ingre.save()
    return redirect('inventory:ingredient')


def deleteIngredient(request):
    """
        Delete Ingredient from database
        input :- Accept Ingredient Id from User
        output :- Redirect To Ingredient List
    """
    msg = "Invalid Ingredient ID"
    if request.method == "GET":
        print("Delete Ingredient Method")
        print("Data :", request.GET.get("deleteElementId"))
        ingre = models.IngredientIndividual.objects.get(id=request.GET.get("deleteElementId"))

        msg = f"Ingredient {ingre.name} with Id {ingre.id} is Deleted Successfully"
        ingre.delete()

    # return redirect('inventory:ingredient')
    return JsonResponse({
        "Status": 200,
        "Message": msg,
    })


#####################################################
############ Items Functions  #################
#####################################################


@cache_control(max_age=3600)
def itemsHome(request):
    """
        Display List of Items
    """
    items = models.ItemIndividual.objects.all()
    ingredients = models.IngredientIndividual.objects.all()
    category = models.Category.objects.all()
    return render(request, 'items.html', {
        "toolbar": True,
        "putPlus": True,
        "active": "items",
        "data": items,
        "options": ingredients,
        "Category": category,
        "queryItem": "item_one",
        "heading": "Items",
    })


def editItems(request,id):
    ingredients = models.IngredientIndividual.objects.all()
    category = models.Category.objects.all()
    l = list()
    data = dict()
    l.append(data)
    temp = list(models.Items.objects.filter(itemId=id))

    try:
        temp100 = models.ItemIndividual.objects.get(id=id)
    except:
        return redirect('inventory:items')

    data["ItemName"] = temp100.name

    if temp100.type == None or temp == "":
        data["type"] = 0
    else:
        data["type"] = temp100.type.id

    if temp100.confirmItem:
        data["lock"] = "Ture"
    else:
        data["lock"] = "False"

    data["ingredient"] = list()

    if len(temp) > 0:
        for i in temp:
            key = models.IngredientIndividual.objects.get(id=i.ingredientId.id)
            data["ingredient"].append({i.ingredientId.id: key.name})

    print("data : ",data)
    print("data : ",id)

    return render(request, 'itemEdit.html',{
        "active": "items",
        "options": ingredients,
        "Category": category,
        "data" : data,
        "id" : id,
        "heading": "Edit Item",
    })

@csrf_exempt
def newItems(request):
    """
        Add New Item to Database
        input :- Takes Series for form data named as ingredientId{i} and value{i} with addidtional argument of
        new item name
    """
    if request.method == "POST":

        bjson = request.POST.get("json")
        itemId = request.POST.get("ItemId")
        tempList = []

        # Get Item if it's Exist else create New
        if itemId == "":
            # New Item Created
            Item = models.ItemIndividual(name=request.POST.get("name"), type_id=request.POST.get("type"))
            Item.save()
        else:
            # update Item Fetch
            Item = models.ItemIndividual.objects.get(id=itemId)
            Item.name = request.POST.get("name")
            Item.type_id = request.POST.get("type")
            Item.modifyAt = timezone.now()
            Item.save()
            tempList = list(models.Items.objects.filter(itemId=Item))

        for key, value in request.POST.items():

            if "ingredientId" in key:
                try:
                    tempIngredient = models.Items.objects.get(itemId=Item, ingredientId_id=value)
                    if tempIngredient in tempList:
                        tempList.remove(tempIngredient)
                except:
                    tempIngredient = models.Items(itemId=Item, ingredientId_id=value)
                    tempIngredient.save()

        # Ingredient Deleted From Items
        for i in tempList:
            i.delete()

        if bjson == "true":
            return JsonResponse({
                "Status": 200,
                "msg": "Data Received",
                "data": {
                    "name": Item.name,
                    "id": Item.id
                }
            })

    return redirect('inventory:items')


def lockItem(request,id):
    # if request.method == 'GET':
    #     return redirect('inventory:items')
    res = {}
    try:
        item = models.ItemIndividual.objects.get(id=id)
        item.confirmItem = not item.confirmItem
        item.save()
        res["status"] = 200
        res["msg"] = "Item update Successfully"
        res["lock"] = item.confirmItem
    except:
        res["status"] = 504
        res["msg"] = "Query Error"
        res["lock"] = None

    return JsonResponse(res)

orderInventory/templates/category.html
{% extends "extendedTemplate.html" %}

{# update Form #}
{% block updateBox %}

    <form action="{% url 'inventory:update_category' %}" method="POST" id="formId">
        {% csrf_token %}
        <div id="updateField">

        </div>
        <input id="updateElementID" name="updateElementID" type="number" style="display:none;">

        <div class="form-element-box">
            <label for="#name" class="from-lable">Category Name</label>
            <div class="form-control">
                <input type="text" required class="from-element" name="name" id="name" placeholder="Enter Store Name">
            </div>
        </div>

        <input type="submit" class="button-remove button-style-1 submit-btn" value="Update">
        <button class="button-remove button-style-1 cancel-btn"> cancel</button>
    </form>

{% endblock %}


{# New Item Form #}
{% block newItemBox %}

    <h1>New {{ heading }}</h1>
    <form action="{% url 'inventory:new_category' %}" method="POST" id="formId">

        {% csrf_token %}

        <div class="form-element-box">
            <label for="#name" class="from-lable">Category Name</label>
            <div class="form-control">
                <input type="text" required class="from-element" name="name" id="name" placeholder="Enter Store Name">
            </div>
        </div>

        <input type="submit" class="button-remove button-style-1 submit-btn" value="Create">
        <button class="button-remove button-style-1 cancel-btn"> cancel</button>
    </form>

{% endblock %}

orderInventory/templates/extendedTemplate.html
{% extends "template.html" %}
{% load static %}
{% block heading %}
{{ heading }}
{% endblock %}
{% block Main %}

    <section class="single-container search-elements display-home-item" id="single-section">
        {% for i in data %}
        <div class="suggetion-list-item">
            <p class="text" data-itemid="{{ i.id }}" data-queryItem="{{ queryItem }}">{{ i.name }} </p>
            <button class="add button-remove">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                    <path d="m18.988 2.012 3 3L19.701 7.3l-3-3zM8 16h3l7.287-7.287-3-3L8 13z"></path>
                    <path
                        d="M19 19H8.158c-.026 0-.053.01-.079.01-.033 0-.066-.009-.1-.01H5V5h6.847l2-2H5c-1.103 0-2 .896-2 2v14c0 1.104.897 2 2 2h14a2 2 0 0 0 2-2v-8.668l-2 2V19z">
                    </path>
                </svg>
            </button>
        </div>

        {% endfor %}
    </section>
<div id="multi-section">

    <section id="section1">

        <div class="toolbox" id="toolbox">
            <div class="search-bar">
                <div class="form-element-box">
                    <div class="form-control">
                        <input type="text" class="from-element search-input" placeholder="Search Element">
                    </div>
                </div>
            </div>
        </div>
        <div class="search-elements">

        {% for i in data %}
        <div class="suggetion-list-item">
            <p class="text" data-itemid="{{ i.id }}" data-queryItem="{{ queryItem }}">{{ i.name }} </p>
            <button class="add button-remove">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                    <path d="m18.988 2.012 3 3L19.701 7.3l-3-3zM8 16h3l7.287-7.287-3-3L8 13z"></path>
                    <path
                        d="M19 19H8.158c-.026 0-.053.01-.079.01-.033 0-.066-.009-.1-.01H5V5h6.847l2-2H5c-1.103 0-2 .896-2 2v14c0 1.104.897 2 2 2h14a2 2 0 0 0 2-2v-8.668l-2 2V19z">
                    </path>
                </svg>
            </button>
        </div>

        {% endfor %}
        </div>
    </section>
    <section class="section2" id="detailBox">
        <h1> Details </h1>
        <ul class="detail-list">
        </ul>
        <button class="button-remove button-style-1 button-style-2 edit" role="button" type="button">Edit</button>
        <button class="button-remove button-style-1 cancel-btn" role="button" type="button" >Cancel</button>

    </section>

    <section class="section2" id="updateBox">
        <h1>Update {{ heading }}</h1>
        {% block updateBox %}
        {% endblock %}
    </section>
</div>

<section class="single-container" id="newItemBox">
    {% block newItemBox %}

    {% endblock %}
</section>
{% endblock %}
{% block scripts %}
    <script src="{% static 'js/script.js' %}"></script>
    <script>
        active = "{{ active }}";
        if (active === "store"){
            document.getElementById("deleteFrom").action = "{% url 'inventory:delete_category' %}";
        }
        else if( active === "ingredient" ){
            document.getElementById("deleteFrom").action = "{% url 'inventory:delete_ingredient' %}";
        }
        else {
            document.getElementById("deleteFrom").action = "{% url 'inventory:home' %}";
        }
    </script>
{% endblock %}

orderInventory/templates/ingredient.html
{% extends 'extendedTemplate.html' %}
{% load static %}
{% block updateBox %}
    <form action="{% url 'inventory:update_ingredient' %}" method="POST" id="formId">
        {% csrf_token %}
        <div id="updateField">

        </div>
        <input id="updateElementID" name="updateElementID" type="number" style="display:none;">
        <div class="form-element-box">
            <label for="#name" class="from-lable">Ingredient Name</label>
            <div class="form-control">
                <input type="text" autocomplete="off" list="autocompleteOff" required class="from-element" name="name" id="name" placeholder="Enter Ingredient Name">
            </div>
        </div>
        <div class="form-element-box">
            <label for="" class="from-lable">Purchase At</label>
            <div class="form-control">
                <select class="from-element" name="categoryId" id="category" required>
                    <option value="---------">-------------</option>
                    {% for d in Category %}
                        <option value="{{ d.id }}">{{ d.name }}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <input type="submit" class="button-remove button-style-1 submit-btn" value="Update">
        <button class="button-remove button-style-1 cancel-btn"> cancel</button>
    </form>
{% endblock %}

{% block newItemBox %}
    <h1>New {{ heading }}</h1>

    <form action="{% url 'inventory:new_ingredient' %}" method="POST" id="formId">
    {%  csrf_token %}
        <div class="form-element-box">
            <label for="#name" class="from-lable">Ingredient Name</label>
            <div class="form-control">
                <input type="text" autocomplete="off" list="autocompleteOff" required class="from-element" name="name" id="name" placeholder="Enter Text">
            </div>
        </div>
        <div class="form-element-box">
            <label for="" class="from-lable">Purchase At</label>
            <div class="form-control">
                <select class="from-element" name="categoryId" required>
                    <option value="0" >-------------</option>
                    {% for d in Category %}
                        <option value="{{ d.id }}">{{ d.name }}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <input type="submit" class="button-remove button-style-1 submit-btn" value="Create">
        <button type="reset" class="button-remove button-style-1 cancel-btn" id="close" >
            close
        </button>
    </form>

{% endblock %}

orderInventory/templates/order.html
{% extends 'template.html' %}
{% load static %}
{% block heading %}
    Order For :- <span id="orderFor">Shiv Chevli</span>
{% endblock %}
{% block Main %}
    <style>
        section{
            max-height: 80vh !important;
        }
        .order-detail{
            margin: 18px 0 !important;
        }
    </style>
    <div id="detail-view">
        <section id="orderDetail-section1">
                <div class="order-detail">
                    <h3>Name :- </h3>
                    <p>{{ data.orderName }}</p>
                </div>
                <div class="order-detail">
                    <h3>Address:- </h3>
                    <p>{{ data.address }} </p>
                </div>
                <div class="order-detail">
                    <h3>Email :- </h3>
                    <p>{{ data.email }}</p>
                </div>
                <div class="order-detail">
                    <h3>Number :- </h3>
                    <p>{{ data.mobileNumber }}</p>
                </div>
                <div class="order-detail">
                    <h3>Order Data & time :- </h3>
                    <p>{{ data.deliverDate }}</p>
                </div>
                <div class="order-detail">
                    <h3>Number of Person</h3>
                    <p>{{ data.numberOfPerson }}</p>
                </div>
                <div class="section4">


                    <a id="backBtn"
                        {% if confirm %}
                            href="{% url 'inventory:orderList' %}"
                        {% else %}
                            href="{% url 'inventory:clientTalksList' %}"
                        {% endif %}
                        class="button-remove button-style-1 cancel-btn">
                        Back
                    </a>

                    <a
                        {% if confirm %}
                            href="{% url 'inventory:orderPrint' data.orderId %}"
                        {% else %}
                            href="{% url 'inventory:orderPrintData' data.orderId "client" %}" target="_blank"
                        {% endif %}
                         class="button-remove  button-style-1 button-style-2 " id="printPdf">
                        Print
                    </a>

                    <button id="lockBtn" onclick="lockOrder({{ data.orderId }})" class="button-remove button-style-1 cancel-btn">
                    {% if confirm  %}
                        Un-lock
                    {% else %}
                        Lock
                    {% endif %}
                    </button>

                    <div id="edit-div"
                    {% if confirm %}
                        style="display: none"
                    {% endif %} >
                    <a href="{% url 'inventory:orderEdit' data.orderId  %}" id="editBtn" class="button-remove button-style-1">
                        Edit
                    </a>
                    <form  style="display: inline-block" method="post" id="deleteOrderFrom" action="{% url 'inventory:delete_order'%}" onsubmit="confirmSubmission(event)">
                        {% csrf_token %}
                        <input type="hidden" value="{{ data.orderId}}" name="orderId">
                        <button class="button-remove  button-style-1 cancel-btn" role="button" type="submit"> Delete</button>
                    </form>
                    </div>

                </div>
            </section>
        <section class="section2" id="section1">
                <h1>Item List</h1>
                <div class="item-list-box">

                    {% for dataItem in data.fields %}
                        <div class="item-box" data-itemid="{{ dataItem.id }}">
                        <h2 class="item-name">
                            <span class="item-name-text">
                                {{ dataItem.name }}
                            </span>
                            <span class="arrow">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                                    <path d="M16.293 9.293 12 13.586 7.707 9.293l-1.414 1.414L12 16.414l5.707-5.707z">
                                    </path>
                                </svg>
                            </span>
                        </h2>
                        <ul class="ingredient-list">
                            {% for key in dataItem.ingredients %}
                                <li data-ingredientId="{{ key.id }}">{{ key.name }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                    {% endfor %}

                </div>
            </section>
    </div>

{% endblock %}

{% block scripts %}
    <script src="{% static 'js/orderScript.js' %}"></script>
    <script>
        function back(){
            window.history.back();
        }
        function confirmSubmission(event) {
            if (confirm("Do you Really want to delete this data ?") == false) {
                return event.preventDefault();
            }
        }

        function lockOrder(orderId){
            let btn = document.querySelector("#lockBtn");
            let backBtn = document.querySelector("#backBtn");
            let frm = document.querySelector("#edit-div");
            let pdf = document.querySelector("#printPdf");
            fetch(`/orderInventory/OrderLock/${orderId}`)
                .then(response => response.json())
                .then(data =>{
                    console.log(data);
                    if(data.lock == true){
                        console.log("order Lock")
                        btn.innerHTML = "Un-lock";
                        frm.style.display = "none";
                        pdf.traget = "_self";
                        pdf.href =`/orderInventory/OrderPrintOptions/${orderId}`;

                        backBtn.href = "/orderInventory/ConfirmOrderList";

                    }
                    else {
                        console.log("order un-Lock")
                        btn.innerHTML = "Lock";
                        frm.style.display = "block";
                        pdf.traget = "_blank";
                        pdf.href =`/orderInventory/OrderPrintData/${orderId}/client`;
                        backBtn.href = "/orderInventory/OrderList";
                    }

                })
            .catch(error=>{
                console.log(error);
            })
        }
    </script>
{% endblock %}